name: Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - develop
    paths:
      - 'src/content/**'
      - 'src/pages/**'
      - 'src/components/**'
      - 'src/styles/**'
      - 'src/config/**'
      - 'public/**'
      - 'astro.config.mjs'
      - 'tailwind.config.mjs'
      - 'package.json'
      - 'pnpm-lock.yaml'
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions:
  deployments: write
  contents: read

jobs:
  deploy:
    name: Deploy web3ready.org
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup
        uses: LumeWeb/workflows/.github/actions/setup-all@develop
      - name: Build
        run: pnpm build
      - name: Deploy to IPFS via Pinner
        id: deploy_pinner
        uses: lumeweb/pinner-deploy-action@v0
        with:
          api-key: ${{ secrets.PINNER_API_KEY }}
          path: dist
          domain: web3ready.org
          remove-previous: true
